# Generated by Django 3.2.10 on 2022-02-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'post'},
        ),
    ]
